// Verifies Cranfield search results against Lucene 9.12.0 ground truth.
// Ground truth file format: term|hitCount|docId1,docId2,...
// Generated by tools/CranfieldGroundTruth.java

#include "minilucene/analysis/simple_analyzer.h"
#include "minilucene/index/index_writer.h"
#include "minilucene/index/segment_reader.h"
#include "minilucene/index/term.h"
#include "minilucene/search/index_searcher.h"
#include "minilucene/search/term_query.h"
#include "minilucene/search/hits.h"
#include "minilucene/document/document.h"
#include "minilucene/document/field.h"
#include "minilucene/store/ram_directory.h"
#include <gtest/gtest.h>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using namespace minilucene;

struct CranDoc { int id; std::string body; };

std::vector<CranDoc> LoadDocs(const std::string& path) {
    std::ifstream f(path);
    std::string line;
    std::vector<CranDoc> docs;
    CranDoc cur; cur.id = 0;
    std::string* target = nullptr;
    while (std::getline(f, line)) {
        if (line.substr(0, 2) == ".I") {
            if (cur.id > 0) { docs.push_back(cur); cur = CranDoc(); }
            cur.id = std::stoi(line.substr(3)); target = nullptr;
        } else if (line == ".W" || line == ".T") { target = &cur.body; }
        else if (line == ".A" || line == ".B") { target = nullptr; }
        else if (target && !line.empty()) {
            if (!target->empty()) *target += " ";
            *target += line;
        }
    }
    if (cur.id > 0) docs.push_back(cur);
    return docs;
}

// Format: term|hitCount|docId1,docId2,...
std::map<std::string, std::pair<int, std::set<int>>> LoadGroundTruth(const std::string& path) {
    std::map<std::string, std::pair<int, std::set<int>>> gt;
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) {
        std::istringstream ss(line);
        std::string term;
        std::getline(ss, term, '|');
        std::string countStr;
        std::getline(ss, countStr, '|');
        int count = std::stoi(countStr);
        std::string ids;
        std::getline(ss, ids);
        std::istringstream idsStream(ids);
        std::string id;
        while (std::getline(idsStream, id, ',')) {
            if (!id.empty()) gt[term].second.insert(std::stoi(id));
        }
        gt[term].first = count;
    }
    return gt;
}

TEST(CranfieldGroundTruth, ExactHitCounts) {
    auto docs = LoadDocs("tests/data/cranfield/cran.all.1400");
    ASSERT_GE(docs.size(), 1390);

    store::RAMDirectory dir;
    auto a = std::make_unique<analysis::SimpleAnalyzer>();
    index::IndexWriter w(dir, std::move(a));
    for (auto& d : docs) {
        document::Document doc;
        doc.Add(document::Field::Text("body", d.body));
        w.AddDocument(doc);
    }
    w.Close();

    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);

    auto gt = LoadGroundTruth("tests/data/cranfield/cran_ground_truth.txt");
    ASSERT_FALSE(gt.empty());

    for (auto& [term, expected] : gt) {
        search::TermQuery tq(index::Term(0, term));
        auto hits = s.Search(tq);
        ASSERT_NE(hits, nullptr) << "term '" << term << "'";
        int got_hits = hits->Length();
        int exp_hits = expected.first;
        EXPECT_NEAR(got_hits, exp_hits, exp_hits * 0.05)
            << "term '" << term << "' hit count: got " << got_hits << " vs Lucene " << exp_hits;
    }
}
