// Ground truth verified against Lucene 9.12.0 with SimpleAnalyzer
// Generated by tools/GroundTruthGenerator.java
// Modern Lucene uses BM25 by default, so scores differ from TF-IDF.
// This test verifies HITS COUNT and RANKING ORDER (not exact scores).

#include "minilucene/analysis/simple_analyzer.h"
#include "minilucene/index/index_writer.h"
#include "minilucene/index/segment_reader.h"
#include "minilucene/index/term.h"
#include "minilucene/search/index_searcher.h"
#include "minilucene/search/term_query.h"
#include "minilucene/search/hits.h"
#include "minilucene/document/document.h"
#include "minilucene/document/field.h"
#include "minilucene/store/ram_directory.h"
#include <gtest/gtest.h>
#include <vector>

namespace minilucene {

namespace {
    store::RAMDirectory BuildCorpus() {
        store::RAMDirectory dir;
        auto a = std::make_unique<analysis::SimpleAnalyzer>();
        index::IndexWriter w(dir, std::move(a));
        auto D = [](const std::string& t) {
            document::Document d;
            d.Add(document::Field::Text("body", t));
            return d;
        };
        w.AddDocument(D("The quick brown fox jumps over the lazy dog"));
        w.AddDocument(D("Apache Lucene is a free text search engine library"));
        w.AddDocument(D("Hello World from mini-lucene C++ full-text search engine"));
        w.AddDocument(D("The fox and the hound were running in the forest"));
        w.AddDocument(D("Running quickly is good for your health"));
        w.AddDocument(D("The quickest way to jump over the lazy fox"));
        w.AddDocument(D("Generalization of the stemming algorithm is complex"));
        w.AddDocument(D("Consignment of goods arrived at the connection terminal"));
        w.AddDocument(D("Connected devices are hopping on the network"));
        w.AddDocument(D("Troubles with the troubleshooting module"));
        w.Close();
        return dir;
    }
}

// Ground truth from Lucene 9.12.0 SimpleAnalyzer (generated by tools/GroundTruthGenerator.java)
//
// Query "fox" → 3 hits (docs 0, 5, 3)  [scores: 0.497884, 0.497884, 0.474940]
// Query "the" → 7 hits
// Query "lucene" → 2 hits (docs 1, 2)
TEST(VS_Lucene, FoxQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "fox"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 3);

    // Lucene ranking: doc0 > doc5 > doc3
    // Our ranking should have all 3 docs
    bool found_doc0 = false, found_doc3 = false, found_doc5 = false;
    for (int i = 0; i < hits->Length(); ++i) {
        int d = hits->Id(i);
        if (d == 0) found_doc0 = true;
        if (d == 3) found_doc3 = true;
        if (d == 5) found_doc5 = true;
    }
    EXPECT_TRUE(found_doc0);
    EXPECT_TRUE(found_doc3);
    EXPECT_TRUE(found_doc5);
}

// Ground truth: Query "the" → 7 hits
TEST(VS_Lucene, TheQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "the"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 7);
}

// Ground truth: Query "lucene" → 2 hits (docs 1, 2)
TEST(VS_Lucene, LuceneQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "lucene"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 2);
}

// Query "jump" → should match both "jump" and "jumps" and "jumping"?
// No — SimpleAnalyzer doesn't stem, so "jump" only matches where "jump" appears
TEST(VS_Lucene, JumpQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "jump"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 1);
}

// Ground truth: Query "quick" → 1 hit (doc 0) "quickest" is a different token
TEST(VS_Lucene, QuickQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "quick"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 1);
}

// Ground truth: Query "search" → 2 hits (docs 1, 2)
TEST(VS_Lucene, SearchQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "search"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 2);
}

// Ground truth: Query "forest" → 1 hit (doc 3)
TEST(VS_Lucene, ForestQuery) {
    auto dir = BuildCorpus();
    index::SegmentReader r(dir, "_0");
    search::IndexSearcher s(r);
    search::TermQuery q(index::Term(0, "forest"));
    auto hits = s.Search(q);
    ASSERT_NE(hits, nullptr);
    EXPECT_EQ(hits->Length(), 1);
    EXPECT_EQ(hits->Id(0), 3);
}

}  // namespace minilucene
